### PR TITLE
Tailwind 3 support

### LINKED ISSUE #53: Tailwind 3 support
Hi,

Thanks for the great package,

It there a plan to support Tailwind 3 as i get this error while installing:

```
npm ERR! While resolving: undefined@undefined
npm ERR! Found: tailwindcss@3.0.7
npm ERR! node_modules/tailwindcss
npm ERR!   dev tailwindcss@"^3.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tailwindcss@"^2.0.3" from litepie-datepicker@1.0.14
npm ERR! node_modules/litepie-datepicker
npm ERR!   litepie-datepicker@"*" from the root project

```

Thanks.

### PR DESCRIPTION
**Pull request by elreco**
`border-opacity` no longer exists with tailwind 3.

closes https://github.com/kenhyuwa/litepie-datepicker/issues/53

### CODE REVIEW

**Comment by tbordinat** [comment]
Nice one !

**Comment by kawoki** [comment]
I think you've just changed the styling in landing page and not the actual datepicker itself

**Comment by m0shiurX** [comment]
@kenhyuwa isn't it maintained?

**Comment by matthewbecker1990** [comment]
@kenhyuwa can you merge this please?

**Comment by brandonleichty** [comment]
@kenhyuwa - thank you for merging this! Can you also update the NPM package with these changes so it can be installed and used with Tailwind 3? 🙏

**Comment by sentiasa** [comment]
@kenhyuwa can you please tag the release (1.0.15) so that the npm package is compliant?

I tried `npm install "https://github.com/kenhyuwa/litepie-datepicker.git#main" --save` but it throws:

`node_modules/vite/dist/node/chunks/dep-689425f3.js:40970:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "litepie-datepicker". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "litepie-datepicker". The package may have incorrect main/module/exports specified in its package.json`

**Pull request merged**
